//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesDeleted
    {
        public int id { get; set; }
        public string name { get; set; }
        public int idColor { get; set; }
        public Nullable<int> idSize { get; set; }
        public Nullable<int> idSizeNumeric { get; set; }
        public double price { get; set; }
        public string description { get; set; }
        public System.DateTime dateDeleted { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Size Size { get; set; }
        public virtual SizeNumeric SizeNumeric { get; set; }
    }
}
