//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public string gender { get; set; }
        public string description { get; set; }
        public double price { get; set; }
        public int stock { get; set; }
    }
}
